apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: example
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: example
        image: rahulreddyravipally/example:v1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32600
  type: NodePort

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: example-url
spec:
  path: /
  to:
    kind: Service
    name: example-service
  port:
    targetPort: 8080